### ISSUE TITLE
Patch release to include new gRPC version

### ISSUE THREAD

**Issue by utkuaydn** [apache/pekko-grpc#254]
Hi, currently we are trying to change our deployment distros to Alpine, however, it seems like there was a glib compatibility [issue](https://github.com/grpc/grpc-java/issues/10096) in grpc-java that caused segmentation faults when trying to build the project. It seems to have been fixed since 1.56.0 but pekko-grpc 1.0.2 is still on 1.54.2. Is it possible to make a patch release so that the dependency gets bumped to fix this issue?

**Comment by raboof** [comment]
We are discussing a new release (https://lists.apache.org/thread/rjygk60ho1mojk4rqsmvd2y4244d55lr) but since Pekko is a fairly new project we have some questions to answer around in what order we want to do updates and which changes should cause major/minor version bumps.

Could you test your project with the snapshots we publish to https://repository.apache.org/content/groups/snapshots/org/apache/pekko/ ? Such feedback would be very valuable!

**Comment by pjfanning** [comment]
We will probably only release the gRPC lib update in Pekko 1.1.0. The protobuf changes are too much for a patch level release. You can build your own pekko-grpc libs from main branch if you like. We have snapshots on repository.apache.org. Main branch uses latest gRPC libs.

**Comment by utkuaydn** [comment]
I understand, then for now we can close this issue. We will test our application with 1.1.0 when it gets released and open a new issue if the problem persists. Thanks for the info :)
