### ISSUE TITLE
Release 1.0.3 with updated protobuf/gRPC?

### ISSUE THREAD

**Issue by dvgica** [apache/pekko-grpc#372]
Hi,

Due to [this CVE](https://nvd.nist.gov/vuln/detail/CVE-2024-7254) I'm working on upgrading protobuf and gRPC libs in several codebases. However, it appears that there isn't yet a pekko-grpc release with `protobuf-java` upgraded to 3.25.3 (I see it's been merged to master [here](https://github.com/apache/pekko-grpc/blob/main/project/Dependencies.scala#L40) though).

I attempted to use upgraded protobuf-java and related io.grpc libs with 1.0.2 anyway, and ran into a bunch of runtime incompatibilities. Any chance of a 1.0.3 release to alleviate this?

Thanks!

**Comment by pjfanning** [comment]
This is a bug tracker. Releases are required by ASF releases to be discussed on the Pekko mailing list. A gRPC 1.1.0 release will be released soon - after the HTTP 1.1.0 release is completed.

We will not be making another other than minor bumps to libs in a potential Pekko gRPC 1.0.3 release. If you want something like that, could you produce a PR with a minor lib bump? Otherwise, you will need to wait for Pekko gRPC 1.1.0.

**Comment by pjfanning** [comment]
https://github.com/advisories/GHSA-735f-pc8j-v9w8 is only so far fixed in 3.25.5 - which is also ready used in Pekko 1.1 snapshots.

If Google can be persuaded to release a new 3.21 release that has this fix, we can consider a Pekko gRPC 1.0.3 that uses that release.

**Comment by dvgica** [comment]
OK, thanks. Will wait for 1.1.0 then.

**Comment by pjfanning** [comment]
There is already a Pekko gRPC 1.1.0-M1 release. It was released before the protobuf 3.25.5 release but it has a 3.25.3 dependency.

We have not heard of any issues with the 1.1.0-M1 releases. If you try them out carefully before going to production, they should be ok. You could use 1.1.0-M1 and force the protobuf jar to upgrade to 3.25.5 in your own build.
